In [8]:

def international_system(n):
 

        def for_tens_ones(t):
          single_digit = [" ",
                          "one ",
                          "two ",
                          "three ",
                          "four ",
                          "five ", 
                          "six ",
                          "seven ",
                          "eight ",
                          "nine "]
           
          double_digit_1 = ["ten ",
                            "eleven ",
                            "twelve ",
                            "thirteen ",
                            "fourteen ",
                            "fifteen ",
                            "sixteen ",
                            "seventeen ", 
                            "eighteen ",
                            "nineteen "]           
 
                
          double_digit_2 = ["",
                            "",
                            "twenty ",
                            "thirty ",
                            "forty ",
                            "fifty ",
                            "sixty ",
                            "seventy ",
                            "eightty ",
                            "ninety"] 

          tens = t // 10
          ones = t % 10     
          if t < 10:
            return(single_digit[t])
          elif t > 9 and t < 20:
            return(double_digit_1[t%10])
          elif t > 19:
            return((double_digit_2[tens]) + single_digit[ones])
        


 
        def for_hundreds(h):
          single_digit = [" ",
                          "one ",
                          "two ",
                          "three ",
                          "four ",
                          "five ",
                          "six ",
                          "seven ",
                          "eight ",
                          "nine "]
           

          hundred = h // 100
          two_digit = h % 100 
          if h > 99:
            return((single_digit[hundred])+ " hundred " +  for_tens_ones(two_digit))
          elif h < 100:
            return for_tens_ones(two_digit)     


 
        billion = n // 1000000000
 
        million = (n // 1000000) % 1000
 
        thousand = (n // 1000) % 1000
 
        hundreds_tens_ones = n % 1000


 
        billion_output =""
        million_output =""
        thousand_output =""
        hundreds_tens_ones_output = ""




        if n < 0:
          return "check number"
        elif n > 0:
          billion_output = for_hundreds(billion) + " billion "
 
          million_output = for_hundreds(million) + " million "
 
          thousand_output = for_hundreds(thousand) + " thousand "  
 
          hundreds_tens_ones_output = for_hundreds(hundreds_tens_ones) 


          output = ""
          output1 = ""
          output2 = ""
          output3 = ""
          output4 = ""
          if billion > 0:
            output1 = billion_output

          if million > 0:
            output2 = million_output  

          if thousand > 0:
            output3 = thousand_output

          if hundreds_tens_ones > 0:  
            output4 = hundreds_tens_ones_output
 
          output = output1 + output2 + output3 + output4
        return output     
 
 
 
input = 123456712
print(international_system(input))

one  hundred twenty three  million four  hundred fifty six  thousand seven  hundred twelve

In [9]:

def indian_system(n):
 

        def for_tens_ones(t):
          single_digit = [" ",
                          "one ",
                          "two ",
                          "three ",
                          "four ",
                          "five ", 
                          "six ",
                          "seven ",
                          "eight ",
                          "nine "]
           
          double_digit_1 = ["ten ",
                            "eleven ",
                            "twelve ",
                            "thirteen ",
                            "fourteen ",
                            "fifteen ",
                            "sixteen ",
                            "seventeen ", 
                            "eighteen ",
                            "nineteen "]           
 
                
          double_digit_2 = ["",
                            "",
                            "twenty ",
                            "thirty ",
                            "forty ",
                            "fifty ",
                            "sixty ",
                            "seventy ",
                            "eightty ",
                            "ninety"] 

          tens = t // 10
          ones = t % 10     
          if t < 10:
            return(single_digit[t])
          elif t > 9 and t < 20:
            return(double_digit_1[t%10])
          elif t > 19:
            return((double_digit_2[tens]) + single_digit[ones])
        




 
        crore = n // 10000000
 
        lakh = (n // 100000) % 100
 
        thousand = (n // 1000) % 100
 
        hundred = (n // 100) % 10

        tens_ones = n%100


 
        crore_output =""
        lakh_output =""
        thousand_output =""
        hundreds_output = ""
        tens_ones_output = ""




        if n < 0:
          return "check number"
        elif n > 0:
          crore_output = for_tens_ones(crore) + " crore "
 
          lakh_output = for_tens_ones(lakh) + " lakh "
 
          thousand_output = for_tens_ones(thousand) + " thousand "  
 
          hundred_output = for_tens_ones(hundred) + " hundred "

          tens_ones_output = for_tens_ones(tens_ones)


          output = ""
          output1 = ""
          output2 = ""
          output3 = ""
          output4 = ""
          output5 = ""


          if crore > 0:
            output1 = crore_output

          if lakh > 0:
            output2 = lakh_output  

          if thousand > 0:
            output3 = thousand_output

          if hundred > 0:  
            output4 = hundred_output

          if tens_ones > 0:
            output5 = tens_ones_output  
 
          output = output1 + output2 + output3 + output4 + output5
        return output     
 
 
 
input = 123456789
print(indian_system(input))

twelve  crore thirty four  lakh fifty six  thousand seven  hundred eightty nine